# Copyright 2025 highstreet technologies USA Corp., University of New Hampshire
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
oran_results_builder.models
~~~~~~~~~~~~~~~~~~~~~~~~~~~

This module includes Pydantic models for O-RAN Test Results Schema (Version 1)
Models are generated by datamodel-code-generator (https://github.com/koxudaxi/datamodel-code-generator)

These classes can be used directly or by utility functions of other modules in this package
"""

# generated by datamodel-codegen:
#   filename:  oran-schema.json
#   timestamp: 2025-04-28T20:43:43+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Literal, Optional, Union
from uuid import UUID

from pydantic import AnyUrl, BaseModel, ConfigDict, EmailStr, Field, RootModel


class TestId(RootModel[str]):
    root: str = Field(
        ...,
        description='Certificate/Badge Reference ID, assigned by the laboratory, in the format of [O-RAN Designator]yy####, where yy is the two digit year, and #### is a four digit number defined by the laboratory.',
        max_length=10,
        min_length=9,
        pattern='^[A-Za-z0-9]{3,4}([23][0-9]){1}[0-9]{4}$',
    )


class Tag(RootModel[str]):
    root: str = Field(..., max_length=255, pattern='^[a-z0-9-]+$')


class Contact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    firstName: str = Field(..., description="Contact's first name.", max_length=255)
    lastName: str = Field(..., description="Contact's last name.", max_length=255)
    organization: Optional[str] = Field(
        None,
        description='Organization or company the contact is associated with.',
        max_length=255,
    )
    email: EmailStr = Field(..., description="Contact's email address", max_length=255)
    phone: Optional[str] = Field(
        None, description="Contact's phone number.", max_length=255
    )


class Contacts(RootModel[List[Contact]]):
    root: List[Contact] = Field(
        ...,
        description='Contact information for person / party involved in the testing or an aspect of the testing.',
    )


class Units(Enum):
    boolean = 'boolean'
    bps = 'bps'
    kbps = 'kbps'
    Mbps = 'Mbps'
    Gbps = 'Gbps'
    dB = 'dB'
    dBm = 'dBm'
    count = 'count'
    millisecond = 'millisecond'
    second = 'second'
    bps_Hz = 'bps/Hz'
    percentage = 'percentage'
    text = 'text'


class ResultType(Enum):
    PASS = 'PASS'
    FAIL = 'FAIL'
    WARN = 'WARN'
    SKIP = 'SKIP'


class TestStatus(Enum):
    mandatory = 'mandatory'
    conditionally_mandatory = 'conditionally.mandatory'
    optional = 'optional'


class DecoratedLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    displayName: str = Field(
        ...,
        description='Text that is displayed as the link when rendered.',
        max_length=255,
    )
    description: Optional[str] = Field(
        None,
        description='Longer, more descriptive text about the link and its contents.',
        max_length=1023,
    )
    url: AnyUrl = Field(..., description='URL Path for the reference.')


class DecoratedLinks(RootModel[List[DecoratedLink]]):
    root: List[DecoratedLink] = Field(
        ...,
        description='A list of links to objects that have a display name, URL, and optionally a description.',
    )


class TestType(Enum):
    conformance = 'conformance'
    interoperability = 'interoperability'
    end_to_end = 'end-to-end'
    Other = 'Other'


class InterfaceUnderTest(Enum):
    o_ru_ofh = 'o-ru.ofh'
    o_ru_fhm = 'o-ru.fhm'
    o_du_ofh = 'o-du.ofh'
    o_du_fhm = 'o-du.fhm'
    o_du_e2 = 'o-du.e2'
    o_du_f1_c = 'o-du.f1-c'
    o_du_f1_u = 'o-du.f1-u'
    o_du_o1 = 'o-du.o1'
    o_cu_f1_c = 'o-cu.f1-c'
    o_cu_f1_u = 'o-cu.f1-u'
    o_cu_e2 = 'o-cu.e2'
    o_cu_e1 = 'o-cu.e1'
    o_cu_o1 = 'o-cu.o1'
    smo_fhm = 'smo.fhm'
    smo_o2 = 'smo.o2'
    smo_o1 = 'smo.o1'
    non_rt_ric_a1 = 'non-rt-ric.a1'
    near_rt_ric_a1 = 'near-rt-ric.a1'
    near_rt_ric_e2 = 'near-rt-ric.e2'
    near_rt_ric_o1 = 'near-rt-ric.o1'


class Artifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ...,
        description='Short name or reference for the file and its contents.',
        max_length=255,
    )
    path: str = Field(
        ...,
        description='Path, relative to the root of the results archieve, to the file or object.',
        max_length=1023,
    )
    description: str = Field(
        ...,
        description='Detailed description of the file and its contents.',
        max_length=4095,
    )


class Artifacts(RootModel[List[Artifact]]):
    root: List[Artifact] = Field(
        ...,
        description='Paths, relative to the root of the archive, to files relating to the test.',
    )


class Measurement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the measurement.', max_length=255)
    description: Optional[str] = Field(
        None, description='Description of the measurement values.', max_length=1023
    )
    values: List = Field(
        ...,
        description='Actual measurement value(s).  Must be an arary, of at least 1 value.  All values must be in the same units.',
        min_length=1,
    )
    units: Units = Field(..., description='Units of the measurement value(s).')
    references: Optional[DecoratedLinks] = Field(
        None,
        description='Link(s) to defintiion of counter or measurement parameter within O-RAN ALLIANCE, 3GPP, or other specification(s).',
    )


class TestNote(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str = Field(..., description='Title of the notecard.', max_length=255)
    body: str = Field(..., description='Content of the notecard.', max_length=4095)


class TestNotes(RootModel[List[TestNote]]):
    root: List[TestNote] = Field(
        ..., description='A list of notes about the parent object.'
    )


class Wg4IotProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    wg4IotSpecificationVersion: str = Field(
        ...,
        description='Version of the O-RAN ALLIANCE WG4.IOT.0 specification containing the profile values.',
        pattern='^[0-9][0-9][.][0-9][0-9]$',
    )
    mPlaneIotProfileName: Optional[str] = Field(
        None,
        description='Name of the M-Plane IOT Profile, as defined within Annex A of the O-RAN ALLIANCE WG4.IOT.0 specification.',
        max_length=128,
        min_length=10,
    )
    mPlaneIotProfileTestConfiguration: Optional[str] = Field(
        None,
        description='Name of the specific test configuration for the M-Plane IOT profile.',
        max_length=128,
        min_length=10,
    )
    cusPlaneIotProfileName: Optional[str] = Field(
        None,
        description='Name of the CUS-Plane IOT Profile, as defined within Annex A of the O-RAN ALLIANCE WG4.IOT.0 specification.',
        max_length=128,
        min_length=10,
    )
    cusPlaneIotProfileTestConfiguration: Optional[str] = Field(
        None,
        description='Name of the specific test configuration for the M-Plane IOT profile.',
        max_length=128,
        min_length=10,
    )


class DeploymentArchitecture(Enum):
    indoor = 'indoor'
    outdoor = 'outdoor'


class DeploymentScale(Enum):
    micro = 'micro'
    pico = 'pico'
    macro = 'macro'


class DeploymentRfScenario(Enum):
    rural = 'rural'
    urban = 'urban'
    dense_urban = 'dense.urban'
    LOS = 'LOS'
    NLOS = 'NLOS'
    nLOS = 'nLOS'


class FrequencyRange5GEnum(Enum):
    fr1 = 'fr1'
    fr2_1 = 'fr2-1'
    fr2_2 = 'fr2-2'
    fr2_ntn = 'fr2-ntn'


class Band5GEnum(Enum):
    n1 = 'n1'
    n2 = 'n2'
    n3 = 'n3'
    n5 = 'n5'
    n7 = 'n7'
    n8 = 'n8'
    n12 = 'n12'
    n13 = 'n13'
    n14 = 'n14'
    n18 = 'n18'
    n20 = 'n20'
    n24 = 'n24'
    n25 = 'n25'
    n26 = 'n26'
    n28 = 'n28'
    n29 = 'n29'
    n30 = 'n30'
    n31 = 'n31'
    n34 = 'n34'
    n38 = 'n38'
    n39 = 'n39'
    n40 = 'n40'
    n41 = 'n41'
    n46 = 'n46'
    n48 = 'n48'
    n50 = 'n50'
    n51 = 'n51'
    n53 = 'n53'
    n54 = 'n54'
    n65 = 'n65'
    n66 = 'n66'
    n70 = 'n70'
    n71 = 'n71'
    n72 = 'n72'
    n74 = 'n74'
    n75 = 'n75'
    n76 = 'n76'
    n77 = 'n77'
    n78 = 'n78'
    n79 = 'n79'
    n80 = 'n80'
    n81 = 'n81'
    n82 = 'n82'
    n83 = 'n83'
    n84 = 'n84'
    n85 = 'n85'
    n86 = 'n86'
    n89 = 'n89'
    n90 = 'n90'
    n91 = 'n91'
    n92 = 'n92'
    n93 = 'n93'
    n94 = 'n94'
    n95 = 'n95'
    n96 = 'n96'
    n97 = 'n97'
    n98 = 'n98'
    n99 = 'n99'
    n100 = 'n100'
    n101 = 'n101'
    n102 = 'n102'
    n103 = 'n103'
    n104 = 'n104'
    n105 = 'n105'
    n106 = 'n106'
    n109 = 'n109'
    n254 = 'n254'
    n255 = 'n255'
    n256 = 'n256'
    n257 = 'n257'
    n258 = 'n258'
    n259 = 'n259'
    n260 = 'n260'
    n261 = 'n261'
    n262 = 'n262'
    n263 = 'n263'
    n510 = 'n510'
    n511 = 'n511'
    n512 = 'n512'


class BandLTEEnum(Enum):
    field_1 = '1'
    field_2 = '2'
    field_3 = '3'
    field_4 = '4'
    field_5 = '5'
    field_6 = '6'
    field_7 = '7'
    field_8 = '8'
    field_9 = '9'
    field_10 = '10'
    field_11 = '11'
    field_12 = '12'
    field_13 = '13'
    field_14 = '14'
    field_16 = '16'
    field_17 = '17'
    field_18 = '18'
    field_19 = '19'
    field_20 = '20'
    field_21 = '21'
    field_22 = '22'
    field_23 = '23'
    field_24 = '24'
    field_25 = '25'
    field_26 = '26'
    field_27 = '27'
    field_28 = '28'
    field_29 = '29'
    field_30 = '30'
    field_31 = '31'
    field_32 = '32'
    field_33 = '33'
    field_34 = '34'
    field_35 = '35'
    field_36 = '36'
    field_37 = '37'
    field_38 = '38'
    field_39 = '39'
    field_40 = '40'
    field_41 = '41'
    field_42 = '42'
    field_43 = '43'
    field_44 = '44'
    field_45 = '45'
    field_46 = '46'
    field_47 = '47'
    field_48 = '48'
    field_49 = '49'
    field_50 = '50'
    field_51 = '51'
    field_52 = '52'
    field_53 = '53'
    field_54 = '54'
    field_55 = '55'
    field_56 = '56'
    field_57 = '57'
    field_58 = '58'
    field_59 = '59'
    field_60 = '60'
    field_61 = '61'
    field_62 = '62'
    field_63 = '63'
    field_64 = '64'
    field_65 = '65'
    field_66 = '66'
    field_67 = '67'
    field_68 = '68'
    field_69 = '69'
    field_70 = '70'
    field_71 = '71'
    field_72 = '72'
    field_73 = '73'
    field_74 = '74'
    field_75 = '75'
    field_76 = '76'
    field_85 = '85'
    field_87 = '87'
    field_88 = '88'
    field_103 = '103'
    field_106 = '106'
    field_107 = '107'
    field_108 = '108'


class SubCarrierSpacing(Enum):
    field_15kHz = '15kHz'
    field_30kHz = '30kHz'
    field_60kHz = '60kHz'


class DuplexMode(Enum):
    tdd = 'tdd'
    fdd = 'fdd'


class ConfigurationParameters(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        serialize_by_alias=True, # TODO - Added manually, need to fix in generator
        populate_by_name=True # TODO - Added manually, need to fix in generator
    )
    deploymentArchitecture: Optional[DeploymentArchitecture] = None
    deploymentScale: Optional[DeploymentScale] = None
    deploymentRfScenario: Optional[DeploymentRfScenario] = None
    frequencyRange5G: Optional[List[FrequencyRange5GEnum]] = Field(None, min_length=1)
    band5G: Optional[List[Band5GEnum]] = Field(None, min_length=1)
    bandLTE: Optional[List[BandLTEEnum]] = Field(None, min_length=1)
    nr_arfcn: Optional[float] = Field(None, alias='nr-arfcn', ge=0.0)
    e_arfcn: Optional[float] = Field(None, alias='e-arfcn', ge=0.0)
    subCarrierSpacing: Optional[SubCarrierSpacing] = None
    totalTransmissionBandwidth: Optional[float] = Field(None, ge=0.0)
    totalResourceBlocks: Optional[int] = Field(None, ge=0)
    carrierPrefixLength: Optional[int] = None
    slotLength: Optional[int] = None
    duplexMode: Optional[DuplexMode] = None
    tddDlUlRatio: Optional[float] = None
    ipv4: Optional[bool] = None
    ipv6: Optional[bool] = None
    numMimoLayers: Optional[int] = Field(None, ge=0)
    numTxAntenna: Optional[int] = Field(None, ge=0)
    numRxAntenna: Optional[int] = Field(None, ge=0)
    totalAntennaGain: Optional[float] = None
    totalTransmitPowerIntoAntenna: Optional[float] = None


class Measurements(RootModel[List[Measurement]]):
    root: List[Measurement] = Field(
        ...,
        description='Test measurements recorded during the test procedure.  Measurements are in addition to values recorded or required as part a test metric.',
        min_length=1,
    )


class TestMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contacts: Optional[Contacts] = Field(
        None,
        description='Contacts relating to the testing, but not necessarily directly relating to the lab or a testbed component.',
    )
    startDate: datetime = Field(..., description='Date and time the test was started.')
    stopDate: Optional[datetime] = Field(
        None, description='Date and time the test was completed.'
    )
    dutName: str = Field(
        ...,
        description='Name or reference to the device(s) in the list of testbed components that is considered the device(s) under test (DUT) or system under test (SUT).',
        max_length=255,
    )
    interfaceUnderTest: Optional[List[InterfaceUnderTest]] = Field(
        None, description='Interface(s) that was under test within these test results.'
    )
    result: ResultType = Field(
        ...,
        description='The overall, aggregated, test result. PASS indicates all required test cases also indicate PASS. FAIL indicates one or more required test cases indicate FAIL. WARN indicates behavior observed during the execution of the test case might cause concern, problems, or issues not directly relating to the required test metrics. SKIP should not be used.',
    )
    testType: TestType = Field(
        ..., description='Type of test result within this artifact.'
    )
    testId: Union[TestId, UUID] = Field(
        ...,
        description='Certificate/Badge Reference ID, assigned by the laboratory, in the format of [O-RAN Designator]yy####, where yy is the two digit year, and #### is a four digit number defined by the laboratory.',
    )
    iotProfile: Optional[Wg4IotProfile] = Field(
        None,
        description='Information about the WG4 IOT profile utilized within the test.',
    )
    configurationParameters: Optional[ConfigurationParameters] = Field(
        None,
        description='General configuration parameters applied to all components in the testbed during the testing.',
    )


class TestbedComponent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    componentDescription: str = Field(
        ...,
        description='Description of the component role with the testing (i.e. O-DU, O-RU, RIC, UE, etc.).',
        max_length=255,
    )
    manufacturerName: str = Field(
        ...,
        description='Company producing the product (hardware or software)',
        max_length=255,
    )
    manufacturerModel: str = Field(
        ...,
        description='Product modle number or other unique identifier.',
        max_length=255,
    )
    serialNumber: Optional[str] = Field(
        None, description='Product serial number.', max_length=255
    )
    testbedInventoryId: Optional[str] = Field(
        None,
        description='Opaque ID number used by lab for invetory management.',
        max_length=255,
    )
    softwareVersion: Optional[str] = Field(
        None,
        description='Software version that was installed during the testing.',
        max_length=255,
    )
    hardwareVersion: Optional[str] = Field(
        None,
        description='Hardware version that was used during the testing.',
        max_length=255,
    )
    firmwareVersion: Optional[str] = Field(
        None,
        description='Firmware version that was installed during the testing.',
        max_length=255,
    )
    contacts: Optional[Contacts] = Field(
        None, description='Company contacts for this product.'
    )
    configurationArtifacts: Optional[Artifacts] = Field(
        None,
        description='Paths, relative to the root of the archive, to configuration files or data relating to this specific testbed component.',
    )
    configurationNotes: Optional[TestNotes] = Field(
        None,
        description='Notes pertaining to the configuration of this testbed component.',
    )
    configurationParameters: Optional[ConfigurationParameters] = Field(
        None, description='Configuration parameters specific to this testbed component.'
    )


class TestLab(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the test lab.', max_length=255)
    address: str = Field(..., description='Address of the test lab.', max_length=512)
    contacts: Contacts = Field(..., description='Contact information for the lab.')
    links: Optional[DecoratedLinks] = Field(
        None, description='Links to additional information provided by the lab.'
    )


class TestSpecification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ..., description='Name of the test specification.', max_length=255
    )
    version: str = Field(
        ..., description='Version of the test specification.', max_length=255
    )
    description: Optional[str] = Field(
        None, description='Description of the test specification.', max_length=512
    )
    links: DecoratedLinks = Field(..., description='Link to the test specification.')


class Metric(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str = Field(
        ...,
        description='Text of the test metric or test requirement, per the test specification.',
        max_length=1023,
    )
    measurements: Measurements = Field(
        ...,
        description='One or more measurements required to determine the outcome of the metric or requirement.',
    )
    status: TestStatus = Field(..., description='Status of the test metric.')
    result: ResultType = Field(
        ...,
        description='Result or outcome of the test metric or requirement.  PASS indicates the requirement of the metric is met.  FAIL indicates the requirement was of the metric was not met.  SKIP indicates the requirement was not evaluated.  WARN value should not be used for metrics.',
    )


class TestCase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    number: str = Field(
        ...,
        description='Test case number, in the format of x[.y].z.',
        max_length=32,
        pattern='^([0-9]+)([.][0-9]+)*$',
    )
    name: str = Field(
        ..., description='The name of the test case or group of tests.', max_length=255
    )
    description: str = Field(
        ...,
        description='A description of the test case or group, stating the purpose or scope.',
        max_length=1023,
    )
    result: ResultType = Field(
        ...,
        description='Result or outcome of the test case.  PASS indicates all required metrics also indicate PASS.  FAIL indicates one or more required metrics indicate FAIL.  SKIP indicates the test case was not executed.  WARN indicates behavior observed during the execution of the test case might cause concern, problems, or issues not directly relating to the required test metrics.',
    )
    status: TestStatus = Field(..., description='Status of the test case.')
    artifacts: Optional[Artifacts] = Field(
        None,
        description='Paths, relative to the root of the archive, to files relating to this specific test case.',
    )
    links: Optional[DecoratedLinks] = Field(
        None,
        description='Links to additional, external documentation specific to the test.',
    )
    measurements: Optional[List[Measurement]] = Field(
        None,
        description='Test measurements recorded during the test procedure.  Measurements are in addition to values recorded or required as part a test metric.',
        min_length=1,
    )
    metrics: List[Metric] = Field(
        ...,
        description='Test metrics or requirements for the test case. (Mandatory for test case)',
        min_length=1,
    )
    notes: Optional[TestNotes] = Field(
        None, description='A list of notes about the test.'
    )
    startDate: Optional[datetime] = Field(
        None, description='Date and time the test case was started.'
    )
    stopDate: Optional[datetime] = Field(
        None, description='Date and time the test case was completed.'
    )
    contacts: Optional[Contacts] = Field(None, description='')


class TestGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    number: str = Field(
        ...,
        description='Test case number, in the format of x[.y].z.',
        max_length=32,
        pattern='^([0-9]+)([.][0-9]+)*$',
    )
    name: str = Field(..., description='Name of the test group.', max_length=255)
    description: Optional[str] = Field(
        None, description='Description of the test group.', max_length=4095
    )
    groupItems: List[Union[TestCase, TestGroup]]


class TestResultsSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: Optional[str] = Field(
        None,
        alias='$schema',
        description='Allow the ojbect to provide a refernece to the schema.',
    )
    schemaVersion: Literal[1] = Field(
        ..., description='Version of the schema file that is applied to these results.'
    )
    testMetadata: TestMetadata
    tags: Optional[List[Tag]] = Field(
        None,
        description='Tags that help describe this tests. These may be used to filter tests.',
    )
    testbedComponents: List[TestbedComponent] = Field(
        ...,
        description='Array of DUT/SUT components, including test and measurement equipment.',
    )
    testLab: TestLab
    testSpecifications: List[TestSpecification] = Field(
        ...,
        description='Array of version controlled documents required for the testing, that can include test specifications, process documentation, and profile documentation.',
    )
    testResults: List[Union[TestGroup, TestCase]] = Field(
        ...,
        description='Array of groups of test cases.  Groups can be nested to represent the hierarchy defined by the test specification.',
    )
    notes: Optional[TestNotes] = Field(
        None, description='A list of notes about the test.'
    )


TestGroup.model_rebuild()
