apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    user: postgres
    password: postgres
    database: testresults
    isDefault: true
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1400  # PostgreSQL 14
      timescaledb: true
    editable: true